//////////////////////////////////////////////////////////////////////////
//errordef.h

//////////////////////////////////////////////////////////////////////////
//generalxmllib.proj
#define ERR_GENERALXMLLIB_START					-90000
#define ERR_CREATE_DOC_FAILED					ERR_GENERALXMLLIB_START-0
#define ERR_LOAD_XMLFILE_FAILED					ERR_GENERALXMLLIB_START-1
#define ERR_SAVE_XMLFILE_FAILED					ERR_GENERALXMLLIB_START-2
#define ERR_GET_ROOTNODE_FAILED					ERR_GENERALXMLLIB_START-3
#define ERR_DOCUMENT_UNEXIST					ERR_GENERALXMLLIB_START-4
#define ERR_GET_DOCUMENT_FAILED					ERR_GENERALXMLLIB_START-5
#define ERR_INTERFACE_UNEXIST					ERR_GENERALXMLLIB_START-6
#define ERR_OUTPUT_NODESTRING_FAILED			ERR_GENERALXMLLIB_START-7
#define ERR_LOADFILE_INVALID					ERR_GENERALXMLLIB_START-8
#define ERR_REMOVE_CHILD_EXCEPTION				ERR_GENERALXMLLIB_START-9
#define ERR_ELEMENT_CONTENT_EMPTY				ERR_GENERALXMLLIB_START-10
#define ERR_CREATE_CHILD_EXCEPTION				ERR_GENERALXMLLIB_START-11
#define ERR_NODE_NAME_EMPTY						ERR_GENERALXMLLIB_START-12
#define ERR_INPUT_INFO_ERROR					ERR_GENERALXMLLIB_START-13
#define ERR_NODE_POINTER_EMPTY					ERR_GENERALXMLLIB_START-14
#define ERR_SOURCE_FLAG_ILLEGAL					ERR_GENERALXMLLIB_START-15
#define ERR_INFO_DIFFER_NODENAME				ERR_GENERALXMLLIB_START-16

//dxmlcore
#define ERR_DXMLCORE_START						-91000
#define ERR_NODE_UNEXIST						ERR_DXMLCORE_START-0
//#define ERR_CREATE_CHILD_FAILED					ERR_DXMLCORE_START-1
#define ERR_REMOVE_CHILD_FAILED					ERR_DXMLCORE_START-1
#define ERR_GET_CHILD_FAILED					ERR_DXMLCORE_START-2
#define ERR_SET_ATTRIBUTE_FAILED				ERR_DXMLCORE_START-3
#define ERR_GET_ATTRIBUTE_FAILED				ERR_DXMLCORE_START-4
#define ERR_REMOVE_ATTRIBUTE_FAILED				ERR_DXMLCORE_START-5
#define ERR_CREATE_CHILDNODE_FAILED				ERR_DXMLCORE_START-6
#define ERR_REMOVE_NODE_EXCEPTION				ERR_DXMLCORE_START-7
#define ERR_GET_NODENAME_FAILED					ERR_DXMLCORE_START-8
#define ERR_SET_TEXTCONTENT_FAILED				ERR_DXMLCORE_START-9
#define ERR_GET_TEXTCONTENT_FAILED				ERR_DXMLCORE_START-10
#define ERR_GET_CHILDCOUNT_EXCEPTION			ERR_DXMLCORE_START-11
#define ERR_GET_CHILD_EXCEPTION					ERR_DXMLCORE_START-12
#define ERR_INSERT_CHILDNODE_FAILED				ERR_DXMLCORE_START-13
#define ERR_OUTOFMEMORY_EXCEPTION				ERR_DXMLCORE_START-14
#define ERR_DOM_EXCEPTION						ERR_DXMLCORE_START-15
#define ERR_XML_EXCPETION						ERR_DXMLCORE_START-16
#define ERR_PARSE_STRING_FAILED					ERR_DXMLCORE_START-17
#define ERR_SAX_EXCEPTION						ERR_DXMLCORE_START-18
#define ERR_GET_LOCALNAME_FAILED				ERR_DXMLCORE_START-19
#define ERR_GET_PREFIXNAME_FAILED				ERR_DXMLCORE_START-20
#define ERR_UNKNOWN_EXCEPTION					ERR_DXMLCORE_START-21

//////////////////////////////////////////////////////////////////////////
//MakeDCPInfo.proj
#define ERR_MAKEDCPINFO_START					-99000
#define ERR_ASSETTYPE_UNDEFINE					ERR_MAKEDCPINFO_START-0		//asset type ??????
#define ERR_MARKER_PARAM_INVALID				ERR_MAKEDCPINFO_START-1		//marker duration????????
#define ERR_GET_MARKERASSET_FAILED				ERR_MAKEDCPINFO_START-2		//????markerasset????
#define ERR_GET_MARKERLIST_FAILED				ERR_MAKEDCPINFO_START-3		//????markerlist????
#define ERR_SET_MARKERINFO_EXCEPTION			ERR_MAKEDCPINFO_START-4		//????marker info ????

#define ERR_ASSET_NOT_EXIST						ERR_MAKEDCPINFO_START-5		//asset ??????
#define ERR_REMOVE_COMPOSITIONPLAYLIST_FAILED	ERR_MAKEDCPINFO_START-6
#define ERR_ASSET_ENCODE_DIFFER					ERR_MAKEDCPINFO_START-7
#define ERR_REEL_UNEXIST						ERR_MAKEDCPINFO_START-8
#define ERR_UPDATE_RATING_BYID_FAILED			ERR_MAKEDCPINFO_START-9
#define ERR_REMOVE_RATING_FAILED				ERR_MAKEDCPINFO_START-10

#define ERR_PACKTYPE_UNEXIST					ERR_MAKEDCPINFO_START-11

#define ERR_WRAP_LENTH_BIGGER					ERR_MAKEDCPINFO_START-12		//wrap length bigger than origin length
