
all:
	make -C GeneralXMLLib/Make_Release  all
	make -C DXMLCore/Make_Release  all
	make -C DCPWrapLib/Make_Release all
	make -C xmldatetime/Make_Release  all

clean:
	make -C GeneralXMLLib/Make_Release clean 
	make -C DXMLCore/Make_Release clean 
	make -C DCPWrapLib/Make_Release clean
	make -C xmldatetime/Make_Release  clean


.PHONY: all clean
