
all:
	make -C DcpParser/Make_Release all
	make -C DcpQuery/Make_Release  all
	make -C DcpReader/reader/Make_Release  all

clean:
	make -C DcpParser/Make_Release  clean
	make -C DcpQuery/Make_Release  clean
	make -C DcpReader/reader/Make_Release  clean


.PHONY: all clean
